<!DOCTYPE orders [
    <!ELEMENT orders (order:order+)>
    <!ATTLIST orders
        xmlns:order CDATA #IMPLIED
        xmlns:prod CDATA #IMPLIED
    >
    <!ELEMENT order:order (prod:item+)>
    <!ATTLIST order:order
        id CDATA #REQUIRED
        customer CDATA #REQUIRED
        date CDATA #REQUIRED
    >
    <!ELEMENT prod:item (prod:name)>
    <!ATTLIST prod:item
        id CDATA #REQUIRED
        quantity CDATA #REQUIRED
        price CDATA #REQUIRED
    >
    <!ELEMENT prod:name (#PCDATA)>
]>
<orders xmlns:order="http://company.com/order" xmlns:prod="http://company.com/product">
    <order:order id="O001" customer="Nguyễn Văn A" date="2025-03-02">
        <prod:item id="P001" quantity="2" price="500">
            <prod:name>Điện thoại Samsung</prod:name>
        </prod:item>
        <prod:item id="P002" quantity="1" price="1000">
            <prod:name>Laptop Dell</prod:name>
        </prod:item>
    </order:order>
    <order:order id="O002" customer="Trần Thị B" date="2025-04-15">
        <prod:item id="P003" quantity="3" price="200">
            <prod:name>Chuột Logitech</prod:name>
        </prod:item>
        <prod:item id="P004" quantity="1" price="1500">
            <prod:name>Màn hình LG</prod:name>
        </prod:item>
        <prod:item id="P001" quantity="1" price="500">
            <prod:name>Điện thoại Samsung</prod:name>
        </prod:item>
    </order:order>
</orders>