<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class [
    <!ELEMENT class (student+)>
    <!ELEMENT student (name, id, subjects)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT subjects (subject+)>
    <!ELEMENT subject (subject_name, score)>
    <!ELEMENT subject_name (#PCDATA)>
    <!ELEMENT score (#PCDATA)>
]>
<class>
    <student>
        <name>Nguyễn Văn A</name>
        <id>SV001</id>
        <subjects>
            <subject>
                <subject_name>Toán</subject_name>
                <score>8.5</score>
            </subject>
            <subject>
                <subject_name>Văn</subject_name>
                <score>7.0</score>
            </subject>
        </subjects>
    </student>
    <student>
        <name>Trần Thị B</name>
        <id>SV002</id>
        <subjects>
            <subject>
                <subject_name>Toán</subject_name>
                <score>9.0</score>
            </subject>
            <subject>
                <subject_name>Tiếng Anh</subject_name>
                <score>8.0</score>
            </subject>
        </subjects>
    </student>
    <student>
        <name>Lê Văn C</name>
        <id>SV003</id>
        <subjects>
            <subject>
                <subject_name>Vật Lý</subject_name>
                <score>7.5</score>
            </subject>
            <subject>
                <subject_name>Hóa Học</subject_name>
                <score>8.2</score>
            </subject>
        </subjects>
    </student>
</class>